---
name: CI

on:
 push:
   branches:
     - master

jobs:
  base:
    name: Push base Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo to have files available
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub to be able to push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: base/context
          push: true
          tags: suckowbiz/base:latest
