---
name: Publish Dockerimage
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      options: --entrypoint sh
    steps:
      - uses: actions/checkout@v1
      - run: ls -l /
