---
name: CI

on:
 push:
   branches:
     - master
 schedule:
   - cron: '0 0 * * *'

jobs:
  base:
    name: Push base Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo to have $GITHUB_WORKSPACE filled with files
        uses: actions/checkout@v2
      -
        name: Log in to Docker Hub to be able to push Docker image
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker image to publish it to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: "$GITHUB_WORKSPACE/base/Dockerfile"
          context: "$GITHUB_WORKSPACE/base/context"
          push: true
          tags: suckowbiz/base:latest
