---
name: Publish Dockerimage
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      volumes:
        - ${{ github.workspace }}:/workspace
      options: --entrypoint sh
    steps:
      - run: echo "unkown" > /etc/dummy-release
      - uses: actions/checkout@v2.3.4
      - run: ls -l /workspace
