---
name: Publish Dockerimage
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
      volumes:
        - ${{ github.workspace }}/.github/workflows/kaniko/config.json:/kaniko/.docker/config.json
        - ${{ github.workspace }}:/workspace
      options: --entrypoint sh
    steps:
      - run: |
          /kaniko/executor \
            --dockerfile=base/Dockerfile \
            --context=dir:///workspace/base/context \
            --destination=suckowbiz/base
